export interface AuthorityPortalConfig {
  authority: string;
  authorityKey: string;
  domain: string;
  complaintUrl: string;
  statusUrl: string;
  instructions: string[];
  fallbackContact?: string;
  descriptionNote?: string;
}

export const AUTHORITY_PORTALS: Record<string, AuthorityPortalConfig> = {
  djb: {
    authority: 'Delhi Jal Board (DJB)',
    authorityKey: 'djb',
    domain: 'delhijalboard.delhi.gov.in',
    complaintUrl: 'https://delhijalboard.delhi.gov.in/',
    statusUrl: 'https://delhijalboard.delhi.gov.in/',
    fallbackContact: 'DJB Customer Care Helpline: 1916 (Toll-Free)',
    descriptionNote:
      'Delhi Jal Board accepts water and sewer complaints through its official grievance portal, the DJB mSeva mobile app, and the 1916 helpline.',
    instructions: [
      'Open the official Delhi Jal Board grievance channel.',
      'Sign in or register on the official portal if required.',
      'Select the water supply or sewerage complaint category.',
      'Paste the complaint text copied from Naagrik AI into the description field.',
      'Add or confirm your locality address and DJB connection / K-No (if available).',
      'Complete the official OTP / CAPTCHA verification steps yourself.',
      'Submit the complaint on the official DJB channel.',
      'Copy the official complaint / reference number issued by DJB.',
      'Return to Naagrik AI and save your reference number for tracking.',
    ],
  },
  mcd: {
    authority: 'Municipal Corporation of Delhi (MCD)',
    authorityKey: 'mcd',
    domain: 'mcdonline.nic.in',
    complaintUrl: 'https://mcdonline.nic.in/pgportal/',
    statusUrl: 'https://mcdonline.nic.in/pgportal/',
    fallbackContact: 'MCD Helpline: 155304 / MCD 311 App',
    descriptionNote:
      'MCD accepts civic grievances regarding sanitation, streetlights, garbage, and public health through the official MCD Online Grievance Portal and MCD 311 App.',
    instructions: [
      'Open the official MCD Online Grievance Portal.',
      'Log in or register with your mobile number.',
      'Select the relevant civic category (Sanitation, Street Lighting, Waste Removal, etc.).',
      'Paste the complaint copied from Naagrik AI into the details box.',
      'Confirm your street address and ward / zone if prompted.',
      'Complete the official OTP / CAPTCHA authentication yourself.',
      'Submit the complaint on the official MCD website.',
      'Copy the official reference number generated by MCD.',
      'Return to Naagrik AI and save your reference number for tracking.',
    ],
  },
  pwd: {
    authority: 'Public Works Department (PWD) Delhi',
    authorityKey: 'pwd',
    domain: 'pwd.delhigovt.nic.in',
    complaintUrl: 'https://pwd.delhigovt.nic.in/',
    statusUrl: 'https://pwd.delhigovt.nic.in/',
    fallbackContact: 'PWD Toll-Free Helpline: 1800-11-0093',
    descriptionNote:
      'PWD Delhi handles major arterial roads, flyovers, road potholes, and drainage along PWD roads.',
    instructions: [
      'Open the official PWD Delhi Grievance portal.',
      'Enter your contact details on the official website form.',
      'Select Road Infrastructure / Pothole / Drainage category.',
      'Paste the official complaint letter copied from Naagrik AI.',
      'Specify the exact road stretch, landmark, or location.',
      'Complete the official government OTP / security verification.',
      'Submit the official grievance on the PWD website.',
      'Copy the official PWD complaint reference ID.',
      'Return to Naagrik AI and save your reference number.',
    ],
  },
  bses: {
    authority: 'BSES Yamuna / Rajdhani Power Limited',
    authorityKey: 'bses',
    domain: 'bsesdelhi.com',
    complaintUrl: 'https://www.bsesdelhi.com/',
    statusUrl: 'https://www.bsesdelhi.com/',
    fallbackContact: 'BSES Helpline: 19123 / WhatsApp: 9999919124',
    descriptionNote:
      'BSES manages electricity supply, transformers, poles, and power outages across Delhi.',
    instructions: [
      'Open the official BSES Delhi Complaint portal or WhatsApp service.',
      'Enter your CA Number or registered mobile number if requested.',
      'Choose No Power / Voltage / Transformer issue category.',
      'Paste your Naagrik AI complaint letter into the issue detail space.',
      'Provide your address and meter details if applicable.',
      'Complete official OTP verification.',
      'Submit your power complaint on the official BSES system.',
      'Copy the official BSES complaint reference number.',
      'Return to Naagrik AI and save your reference number.',
    ],
  },
  traffic_police: {
    authority: 'Delhi Traffic Police',
    authorityKey: 'traffic_police',
    domain: 'traffic.delhipolice.gov.in',
    complaintUrl: 'https://traffic.delhipolice.gov.in/',
    statusUrl: 'https://traffic.delhipolice.gov.in/',
    fallbackContact: 'Delhi Traffic Helpline: 1095 / 011-25844444',
    descriptionNote:
      'Delhi Traffic Police manages traffic signals, traffic congestion, and road safety enforcement.',
    instructions: [
      'Open the official Delhi Traffic Police complaint channel.',
      'Access the traffic issue feedback / grievance portal.',
      'Choose Traffic Signal / Congestion / Enforcement issue.',
      'Paste the Naagrik AI complaint letter into the report box.',
      'Mark the exact intersection or road location.',
      'Enter required contact information and complete verification.',
      'Submit the report on the official traffic portal.',
      'Copy the official complaint reference number.',
      'Return to Naagrik AI and save your reference number.',
    ],
  },
  dda: {
    authority: 'Horticulture Department / DDA',
    authorityKey: 'dda',
    domain: 'dda.gov.in',
    complaintUrl: 'https://dda.gov.in/',
    statusUrl: 'https://dda.gov.in/',
    fallbackContact: 'DDA Public Grievance Helpline: 1800-110-332',
    descriptionNote:
      'Delhi Development Authority (DDA) handles DDA public parks, horticulture, and DDA housing infrastructure.',
    instructions: [
      'Open the official DDA Public Grievance Portal.',
      'Log in or create a user account on the official portal.',
      'Select Horticulture / Public Park / Infrastructure category.',
      'Paste the complaint text copied from Naagrik AI.',
      'Specify the park name, sector, or DDA colony location.',
      'Complete official security verification (CAPTCHA/OTP).',
      'Submit your official DDA grievance.',
      'Copy the official DDA grievance reference ID.',
      'Return to Naagrik AI and save your reference number.',
    ],
  },
  nhai: {
    authority: 'National Highways Authority of India (NHAI)',
    authorityKey: 'nhai',
    domain: 'nhai.gov.in',
    complaintUrl: 'https://nhai.gov.in/',
    statusUrl: 'https://nhai.gov.in/',
    fallbackContact: 'NHAI National Helpline: 1033 (Toll-Free)',
    descriptionNote:
      'NHAI manages National Highways, expressways, toll plazas, and highway road maintenance across India.',
    instructions: [
      'Open the official NHAI Highway Portal or Rajmarg Yatra app.',
      'Register or log in on the official highway portal.',
      'Select National Highway Maintenance / Toll / Safety category.',
      'Paste the formal complaint text from Naagrik AI.',
      'Indicate the highway number (e.g. NH-48) or kilometer marker.',
      'Complete official OTP verification.',
      'Submit the grievance on the official NHAI platform.',
      'Copy your official NHAI complaint reference number.',
      'Return to Naagrik AI and save your reference number.',
    ],
  },
};

export function getAuthorityPortal(authorityKey?: string, authorityName?: string): AuthorityPortalConfig {
  if (authorityKey && AUTHORITY_PORTALS[authorityKey.toLowerCase()]) {
    return AUTHORITY_PORTALS[authorityKey.toLowerCase()];
  }
  const nameLower = (authorityName || '').toLowerCase();
  if (nameLower.includes('jal board') || nameLower.includes('djb')) return AUTHORITY_PORTALS.djb;
  if (nameLower.includes('pwd')) return AUTHORITY_PORTALS.pwd;
  if (nameLower.includes('bses') || nameLower.includes('power')) return AUTHORITY_PORTALS.bses;
  if (nameLower.includes('traffic')) return AUTHORITY_PORTALS.traffic_police;
  if (nameLower.includes('dda') || nameLower.includes('park') || nameLower.includes('horticulture')) return AUTHORITY_PORTALS.dda;
  if (nameLower.includes('nhai') || nameLower.includes('highway')) return AUTHORITY_PORTALS.nhai;

  return AUTHORITY_PORTALS.mcd;
}

